a=98
b=2
c=a+b
print(a,"+",b,"=",a+b)
print(f'{a} + {b} = {a+b}')
print(f'{a} - {b} = {a-b}')
print(f'{a} * {b} = {a*b}')
print(f'{a} / {b} = {a/b}')
print(f'{a} ** {b} = {a**b}')
print(f'{a} // {b} = {a//b}')